services:
  resple:
    image: resple:jazzy
    container_name: resple_jazzy
    user: user
    network_mode: host
    ipc: host
    privileged: true
    tty: true
    stdin_open: true
    
    volumes:
      # Map the workspace
      - ..:/home/user/workspace/src/RESPLE
      - ../build:/home/user/workspace/build
      - ../install:/home/user/workspace/install
      - ../log:/home/user/workspace/log
      # Graphics (X11)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/user/.Xauthority:rw
      # Datasets
      - ../../datasets:/home/user/workspace/datasets:rw

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri # Hardware acceleration

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/user/.Xauthority
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      - ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
      - "RCUTILS_CONSOLE_OUTPUT_FORMAT=[{name}] [{severity}]: {message}"
      - RCUTILS_COLORIZED_OUTPUT=1
      - TERM=xterm-256color
      - COLORTERM=truecolor